openapi: 3.0.3
info:
  title: Nullable example
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/test:
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        alias:
          type: string
          nullable: true
      required:
        - name
        - alias
      additionalProperties: false
